export const CREATE_EPISODE = "CREATE_EPISODE";
export const LOAD_EPISODES_SUCCESS = "LOAD_EPISODES_SUCCESS";
export const CREATE_EPISODE_SUCCESS = "CREATE_EPISODE_SUCCESS";
export const UPDATE_EPISODE_SUCCESS = "UPDATE_EPISODE_SUCCESS";
export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
export const BEGING_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const DELETE_EPISODE_OPTIMISTIC = "DELETE_EPISODE_OPTIMISTIC";
