export const CREATE_EPISODE = "CREATE_EPISODE";
export const LOAD_EPISODES_SUCCESS = "LOAD_EPISODES_SUCCESS";
export const CREATE_EPISODE_SUCCESS = "CREATE_EPISODE_SUCCESS";
export const UPDATE_EPISODE_SUCCESS = "UPDATE_EPISODE_SUCCESS";

export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
